chore(93): Upgrade actions version in CI/CD jobs (#95)

diff --git a/.github/workflows/merge-check.yml b/.github/workflows/merge-check.yml
--- a/.github/workflows/merge-check.yml
+++ b/.github/workflows/merge-check.yml
@@ -10,20 +10,20 @@ jobs:
 
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Set up Node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
           node-version: 18
-          cache: 'npm'
+          cache: "npm"
 
       - name: Install dependencies
         run: npm install
 
       - name: Run tests
         run: npm test
-      
+
       - name: Review Code Quality
         run: npm run lint
 
@@ -32,18 +32,17 @@ jobs:
 
       - name: The job has failed
         if: ${{ failure() }}
-        run: 
-          echo "::error::Pull Request cannot be merged due to failed checks." && exit 1
-  
+        run: echo "::error::Pull Request cannot be merged due to failed checks." && exit 1
+
   storybook-check:
     timeout-minutes: 60
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Set up Node
-        uses: actions/setup-node@v3
+        uses: actions/setup-node@v4
         with:
           node-version: 18
 
@@ -61,8 +60,7 @@ jobs:
           npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
             "npx http-server storybook-static --port 6006 --silent" \
             "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"
-      
+
       - name: The job has failed
         if: ${{ failure() }}
-        run: 
-          echo "::error::Pull Request cannot be merged due to failed storybook check." && exit 1
+        run: echo "::error::Pull Request cannot be merged due to failed storybook check." && exit 1
