Add failure validation for Storybook check

diff --git a/.github/workflows/merge-check.yml b/.github/workflows/merge-check.yml
--- a/.github/workflows/merge-check.yml
+++ b/.github/workflows/merge-check.yml
@@ -61,3 +61,8 @@ jobs:
           npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
             "npx http-server storybook-static --port 6006 --silent" \
             "npx wait-on tcp:127.0.0.1:6006 && npm run test-storybook"
+      
+      - name: The job has failed
+        if: ${{ failure() }}
+        run: 
+          echo "::error::Pull Request cannot be merged due to failed storybook check." && exit 1
