Fix error message

diff --git a/.github/workflows/merge-check.yml b/.github/workflows/merge-check.yml
--- a/.github/workflows/merge-check.yml
+++ b/.github/workflows/merge-check.yml
@@ -29,4 +29,5 @@ jobs:
 
       - name: The job has failed
         if: ${{ failure() }}
-        run: echo "Error: Pull Request cannot be merged due to failed checks." && exit 1
+        run: 
+          echo "::error::Pull Request cannot be merged due to failed checks." && exit 1
