Add step to show a message when any of the other steps has failed

diff --git a/.github/workflows/merge-check.yml b/.github/workflows/merge-check.yml
--- a/.github/workflows/merge-check.yml
+++ b/.github/workflows/merge-check.yml
@@ -26,3 +26,7 @@ jobs:
       
       - name: Review Code Quality
         run: npm run lint
+
+      - name: The job has failed
+        if: ${{ failure() }}
+        run: echo "Error: Pull Request cannot be merged due to failed checks." && exit 1
